### ISSUE TITLE
Can we add an API to reconstruct the header programmatically?

### ISSUE THREAD

**Issue by aruprakshit** [CatanaCorp/github_diff_parser#12]
When we are parsing a Hunk header like this `@@ -6,9 +6,11 @@ def add(string)`, we are only capturing `previous_lino_start` for e.g. -6, [`new_lino_start`](https://github.com/CatanaCorp/github_diff_parser/blob/c6572c88c9c00e3a892e2097dff1cca497687501/lib/github_diff_parser/regexes.rb#L117C12-L117C26) for example +6. So we are missing important information like `def add(string)`, and total line changes like 9, 11 etc. I think the lib should add API to reconstruct the header in case someone want it.

**Comment by Edouard-chin** [comment]
That make sense. I merged https://github.com/CatanaCorp/github_diff_parser/pull/13 which should address your use case.
